apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tei-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/komal-sarvam/modelsync-gitops-argocd.git
    targetRevision: main
    path: helm/tei
    helm:
      valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
